# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coclust <- function(xMat, myList, kr, kc, init, nbSEM, nbSEMburn, nbRepeat, nbindmini, m) {
    .Call('_ordinalClust_coclust', PACKAGE = 'ordinalClust', xMat, myList, kr, kc, init, nbSEM, nbSEMburn, nbRepeat, nbindmini, m)
}

clust <- function(xMat, myList, kr, init, nbSEM, nbSEMburn, nbindmini, m) {
    .Call('_ordinalClust_clust', PACKAGE = 'ordinalClust', xMat, myList, kr, init, nbSEM, nbSEMburn, nbindmini, m)
}

classif <- function(xMat, yVec, myList, kr, kc, init, nbSEM, nbSEMburn, nbindmini, m) {
    .Call('_ordinalClust_classif', PACKAGE = 'ordinalClust', xMat, yVec, myList, kr, kc, init, nbSEM, nbSEMburn, nbindmini, m)
}

classifM <- function(xMat, yVec, myList, kr, init, nbSEM, nbSEMburn, nbindmini, m) {
    .Call('_ordinalClust_classifM', PACKAGE = 'ordinalClust', xMat, yVec, myList, kr, init, nbSEM, nbSEMburn, nbindmini, m)
}

prediction <- function(classif, xMat_topredict) {
    .Call('_ordinalClust_prediction', PACKAGE = 'ordinalClust', classif, xMat_topredict)
}

allej <- function(j, m) {
    .Call('_ordinalClust_allej', PACKAGE = 'ordinalClust', j, m)
}

pejp1zj1_ej <- function(ejp1Vec, ejVec, mu, p) {
    .Call('_ordinalClust_pejp1zj1_ej', PACKAGE = 'ordinalClust', ejp1Vec, ejVec, mu, p)
}

pejp1_ej <- function(ejp1Vec, ejVec, mu, p) {
    .Call('_ordinalClust_pejp1_ej', PACKAGE = 'ordinalClust', ejp1Vec, ejVec, mu, p)
}

pej <- function(ejVec, j, m, mu, p, z1tozjm1Vec) {
    .Call('_ordinalClust_pej', PACKAGE = 'ordinalClust', ejVec, j, m, mu, p, z1tozjm1Vec)
}

