# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_ordinalClust_rcpp_hello_world', PACKAGE = 'ordinalClust')
}

unsigned_to_signed <- function(x) {
    .Call('_ordinalClust_unsigned_to_signed', PACKAGE = 'ordinalClust', x)
}

compare_vec <- function(vec1, vec2) {
    .Call('_ordinalClust_compare_vec', PACKAGE = 'ordinalClust', vec1, vec2)
}

allej <- function(j, m) {
    .Call('_ordinalClust_allej', PACKAGE = 'ordinalClust', j, m)
}

pejp1_yjej <- function(ejp1, yj, ej, mu, p) {
    .Call('_ordinalClust_pejp1_yjej', PACKAGE = 'ordinalClust', ejp1, yj, ej, mu, p)
}

pejp1zj1_yjej <- function(ejp1, yj, ej, mu, p) {
    .Call('_ordinalClust_pejp1zj1_yjej', PACKAGE = 'ordinalClust', ejp1, yj, ej, mu, p)
}

pejp1zj1_ej <- function(ejp1, ej, mu, p) {
    .Call('_ordinalClust_pejp1zj1_ej', PACKAGE = 'ordinalClust', ejp1, ej, mu, p)
}

pyj_ej <- function(yj, ej) {
    .Call('_ordinalClust_pyj_ej', PACKAGE = 'ordinalClust', yj, ej)
}

pejp1_ej <- function(ejp1, ej, mu, p) {
    .Call('_ordinalClust_pejp1_ej', PACKAGE = 'ordinalClust', ejp1, ej, mu, p)
}

pej <- function(ej, j, m, mu, p, z1tozjm1) {
    .Call('_ordinalClust_pej', PACKAGE = 'ordinalClust', ej, j, m, mu, p, z1tozjm1)
}

ordiemCpp <- function(m, tab_pej, x, tabmu0, tabp0, eps = 1, iter_max = 100L) {
    .Call('_ordinalClust_ordiemCpp', PACKAGE = 'ordinalClust', m, tab_pej, x, tabmu0, tabp0, eps, iter_max)
}

